/* Automated test driver for Lab 03. DO NOT EDIT THIS FILE. */
public class Lab03GradeAdvisorTest {

    public static void main(String[] args) {

        String out;

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "87\n2024\n");
        TestRunner.section("Case 1 - score 87, year 2024");
        TestRunner.checkOutputContains("Grade B", out, "Letter grade: B");
        TestRunner.checkOutputContains("Status PASS", out, "Status: PASS");
        TestRunner.checkOutputContains("2024 is a leap year", out, "2024 is a leap year");

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "58\n1900\n");
        TestRunner.section("Case 2 - score 58, year 1900 (century, not a leap year)");
        TestRunner.checkOutputContains("Grade F", out, "Letter grade: F");
        TestRunner.checkOutputContains("Status FAIL", out, "Status: FAIL");
        TestRunner.checkOutputContains("1900 is not a leap year", out, "1900 is not a leap year");

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "70\n2000\n");
        TestRunner.section("Case 3 - boundary score 70, year 2000 (divisible by 400)");
        TestRunner.checkOutputContains("Grade C at the boundary", out, "Letter grade: C");
        TestRunner.checkOutputContains("Status PASS at the boundary", out, "Status: PASS");
        TestRunner.checkOutputContains("2000 is a leap year", out, "2000 is a leap year");
        TestRunner.checkOutputLacks("2000 not reported as non-leap", out, "2000 is not a leap year");

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "90\n2023\n");
        TestRunner.section("Case 4 - boundary score 90, year 2023");
        TestRunner.checkOutputContains("Grade A at the boundary", out, "Letter grade: A");
        TestRunner.checkOutputContains("2023 is not a leap year", out, "2023 is not a leap year");

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "105\n2020\n");
        TestRunner.section("Case 5 - invalid score 105");
        TestRunner.checkOutputContains("Invalid score reported", out, "Invalid score");
        TestRunner.checkOutputLacks("No letter grade for invalid input", out, "Letter grade:");
        TestRunner.checkOutputLacks("No status for invalid input", out, "Status:");
        TestRunner.checkOutputContains("Leap year still evaluated", out, "2020 is a leap year");

        out = TestRunner.runMain(Lab03GradeAdvisor::main, "-4\n2019\n");
        TestRunner.section("Case 6 - invalid negative score");
        TestRunner.checkOutputContains("Invalid score reported", out, "Invalid score");
        TestRunner.checkOutputLacks("No letter grade for invalid input", out, "Letter grade:");

        TestRunner.exitWithSummary();
    }
}
